### PR TITLE
Juliav1.0

### PR DESCRIPTION
**Pull request by jlapeyre**
This PR upgrades SchattenNorms.jl for Julia v1.0.

### CODE REVIEW

**Comment by matthewware** [comment]
I'll have to do some more looking around to see why the diamond test is failing...

**Comment by matthewware** [comment]
So I think some up-stream changes are causing some slight differences in the numerics.  I was able to get all tests to pass 70% of the time.  The other 30% failed in the same way with the same numerical values off by the last digit of tolerance.  For me its when the computed values of the `norm` and the `ddist` are compared.  I'll need to see what's changed in the Convex.jl code base...

**Comment by jlapeyre** [comment]
Me too. I guess it is this one
```
maximal dnorm examples, random |   18     18
dnorm for Pauli channels: Test Failed at /home/lapeyre/.julia/dev/SchattenNorms/test/test-dnorm.jl:99
  Expression: isapprox(pauli_dnorm, calc_dnorm1, atol=1.0e-5)
   Evaluated: isapprox(0.61187159697893, 0.6118557639635327; atol=1.0e-5)
```
I see this with a few matrices occasionally. Mostly this one. And it appears to be  ~`pauli_dnorm`~ `ddist` that differs by the tolerance (sometimes) from run to run.

**Comment by matthewware** [comment]
Ah!  I totally for got about this PR.  Looks like I duplicated a lot of your work with another PR.  On the one hand I was able to track down the numerical issues across OSes (see: https://github.com/JuliaOpt/SCS.jl/issues/114), but now I need to merge the two PRs.

**Comment by jlapeyre** [comment]
>  I need to merge the two PRs.

Argh... That's unfortunate. I hope there are not too many collisions.

> I was able to track down the numerical issues across OSes

Good.

I also forgot it was not merged. I'm still interested in helping; The BBN repos are probably the best QI packages in Julia. But, I'm spread a bit thin ~at the moment~ always.

**Pull request merged**
